POWERLEVEL9K_COLOR_SCHEME='light'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vcs time vi_mode)

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='/ >'
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=':'
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''

POWERLEVEL9K_HIDE_BRANCH_ICON=true

POWERLEVEL9K_CONTEXT_BACKGROUND='brwhite'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='brwhite'
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND='brwhite'
POWERLEVEL9K_CONTEXT_FOREGROUND='brblue'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='brblue'
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='red'

POWERLEVEL9K_DIR_BACKGROUND='brwhite'
POWERLEVEL9K_DIR_FOREGROUND='brblue'
POWERLEVEL9K_TIME_BACKGROUND='brwhite'
POWERLEVEL9K_TIME_FOREGROUND='brblue'

POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='brwhite'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='blue'
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='brwhite'
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='brblue'

POWERLEVEL9K_VCS_BACKGROUND='brwhite'
POWERLEVEL9K_VCS_FOREGROUND='brblue'
POWERLEVEL9K_VCS_DARK_FOREGROUND='red'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='brwhite'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='red'
